name: food_finder
description: A food recognition app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.6
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^1.0.4
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  supabase_flutter: ^2.3.4
  equatable: ^2.0.5
  image: ^4.1.3
  flutter_web_plugins:
    sdk: flutter
  uuid: ^3.0.7
  intl: ^0.18.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true